using System.Collections.Generic;

namespace AltarHelper
{
    internal static class AltarModsConstants
    {
        public static Dictionary<string, AffectedTarget> FilterTargetDict { get; } = new Dictionary<string, AffectedTarget> {
            { "Any", AffectedTarget.Any },
            { "Player", AffectedTarget.Player },
            { "Minion", AffectedTarget.Minions },
            { "Boss", AffectedTarget.FinalBoss }
        };
        public static Dictionary<string, AffectedTarget> AltarTargetDict { get; } = new Dictionary<string, AffectedTarget> {
            { "Player gains:", AffectedTarget.Player },
            { "Eldritch Minions gain:", AffectedTarget.Minions },
            { "Map boss gains:", AffectedTarget.FinalBoss }
        };
    }
    public enum AltarUpsidesPlayer
    {
        Player_IIQ_IIR,
        Player_Gains_DuplicationChance_BasicCurrency,
        Player_Gains_DuplicationChance_Gems,
        Player_Gains_DuplicationChance_Uniques,
        Player_Gains_DuplicationChance_Scarabs,
        Player_Gains_DuplicationChance_Maps,
        Player_Gains_DuplicationChance_DivCards,
    }
    public enum AltarUpsidesBoss
    {
        //Currency
        Boss_Drops_DivineOrbs,
        Boss_Drops_ExaltedOrbs,
        Boss_Drops_RegalOrbs,
        Boss_Drops_ChaosOrbs,
        Boss_Drops_VeiledChaosOrbs,
        Boss_Drops_AlterationOrbs,
        Boss_Drops_BlessedOrbs,
        Boss_Drops_ScouringOrbs,
        Boss_Drops_ChromaticOrbs,
        Boss_Drops_FusingOrbs,
        Boss_Drops_JewellersOrbs,
        Boss_Drops_AwakenedSextants,
        Boss_Drops_BindingOrbs,
        Boss_Drops_HorizonOrbs,
        Boss_Drops_UnmakingOrbs,
        Boss_Drops_AnnulmentOrbs,
        Boss_Drops_VaalOrbs,
        Boss_Drops_EnkindlingOrbs,
        Boss_Drops_InstillingOrbs,
        Boss_Drops_RegretOrbs,
        Boss_Drops_GlassblowerBaubles,
        Boss_Drops_GemcuttersPrisms,
        Boss_Drops_CartographersChisels,
        Boss_Drops_LesserEldritchEmbers,
        Boss_Drops_GreaterEldritchEmbers,
        Boss_Drops_GrandEldritchEmbers,
        Boss_Drops_LesserEldritchIchors,
        Boss_Drops_GreaterEldritchIchors,
        Boss_Drops_GrandEldritchIchors,
        Boss_Drops_EldritchChaosOrbs,
        Boss_Drops_EldritchExaltedOrbs,
        Boss_Drops_EldritchAnnulmentOrbs,
        //Scarabs
        Boss_Drops_Rusted_Breach_Scarab,
        Boss_Drops_Polished_Breach_Scarab,
        Boss_Drops_Gilded_Breach_Scarab,
        Boss_Drops_Rusted_Elder_Scarab,
        Boss_Drops_Polished_Elder_Scarab,
        Boss_Drops_Gilded_Elder_Scarab,
        Boss_Drops_Rusted_Sulphite_Scarab,
        Boss_Drops_Polished_Sulphite_Scarab,
        Boss_Drops_Gilded_Sulphite_Scarab,
        Boss_Drops_Rusted_Ambush_Scarab,
        Boss_Drops_Polished_Ambush_Scarab,
        Boss_Drops_Gilded_Ambush_Scarab,
        Boss_Drops_Rusted_Harbinger_Scarab,
        Boss_Drops_Polished_Harbinger_Scarab,
        Boss_Drops_Gilded_Harbinger_Scarab,
        Boss_Drops_Rusted_Expedition_Scarab,
        Boss_Drops_Polished_Expedition_Scarab,
        Boss_Drops_Gilded_Expedition_Scarab,
        Boss_Drops_Rusted_Legion_Scarab,
        Boss_Drops_Polished_Legion_Scarab,
        Boss_Drops_Gilded_Legion_Scarab,
        Boss_Drops_Rusted_Abyss_Scarab,
        Boss_Drops_Polished_Abyss_Scarab,
        Boss_Drops_Gilded_Abyss_Scarab,
        Boss_Drops_Rusted_Bestiary_Scarab,
        Boss_Drops_Polished_Bestiary_Scarab,
        Boss_Drops_Gilded_Bestiary_Scarab,
        Boss_Drops_Rusted_Torment_Scarab,
        Boss_Drops_Polished_Torment_Scarab,
        Boss_Drops_Gilded_Torment_Scarab,
        Boss_Drops_Rusted_Metamorph_Scarab,
        Boss_Drops_Polished_Metamorph_Scarab,
        Boss_Drops_Gilded_Metamorph_Scarab,
        Boss_Drops_Rusted_Blight_Scarab,
        Boss_Drops_Polished_Blight_Scarab,
        Boss_Drops_Gilded_Blight_Scarab,
        Boss_Drops_Rusted_Reliquary_Scarab,
        Boss_Drops_Polished_Reliquary_Scarab,
        Boss_Drops_Gilded_Reliquary_Scarab,
        Boss_Drops_Rusted_Divination_Scarab,
        Boss_Drops_Polished_Divination_Scarab,
        Boss_Drops_Gilded_Divination_Scarab,
        Boss_Drops_Rusted_Shaper_Scarab,
        Boss_Drops_Polished_Shaper_Scarab,
        Boss_Drops_Gilded_Shaper_Scarab,
        Boss_Drops_Rusted_Cartography_Scarab,
        Boss_Drops_Polished_Cartography_Scarab,
        Boss_Drops_Gilded_Cartography_Scarab,
        //Div Cards
        Boss_Drops_DivCard_Rewards_Currency,
        Boss_Drops_DivCard_Rewards_BasicCurrency,
        Boss_Drops_DivCard_Rewards_LeagueCurrency,
        Boss_Drops_DivCard_Rewards_OtherDivCards,
        Boss_Drops_DivCard_Rewards_Gems,
        Boss_Drops_DivCard_Rewards_LevelledGems,
        Boss_Drops_DivCard_Rewards_QualityGems,
        Boss_Drops_DivCard_Rewards_Unique,
        Boss_Drops_DivCard_Rewards_UniqueWeapon,
        Boss_Drops_DivCard_Rewards_UniqueArmour,
        Boss_Drops_DivCard_Rewards_UniqueJewellery,
        Boss_Drops_DivCard_Rewards_CorruptedUnique,
        Boss_Drops_DivCard_Rewards_Map,
        Boss_Drops_DivCard_Rewards_UniqueMap,
        Boss_Drops_DivCard_Rewards_CorruptedItem,
    }
    public enum AltarUpsidesMinions
    {
        //Currency
        Minion_Drops_DivineOrbs,
        Minion_Drops_ExaltedOrbs,
        Minion_Drops_RegalOrbs,
        Minion_Drops_ChaosOrbs,
        Minion_Drops_VeiledChaosOrbs,
        Minion_Drops_AlterationOrbs,
        Minion_Drops_BlessedOrbs,
        Minion_Drops_ScouringOrbs,
        Minion_Drops_ChromaticOrbs,
        Minion_Drops_FusingOrbs,
        Minion_Drops_JewellersOrbs,
        Minion_Drops_AwakenedSextants,
        Minion_Drops_BindingOrbs,
        Minion_Drops_HorizonOrbs,
        Minion_Drops_UnmakingOrbs,
        Minion_Drops_AnnulmentOrbs,
        Minion_Drops_VaalOrbs,
        Minion_Drops_EnkindlingOrbs,
        Minion_Drops_InstillingOrbs,
        Minion_Drops_RegretOrbs,
        Minion_Drops_GlassblowerBaubles,
        Minion_Drops_GemcuttersPrisms,
        Minion_Drops_LesserEldritchEmbers,
        Minion_Drops_GreaterEldritchEmbers,
        Minion_Drops_GrandEldritchEmbers,
        Minion_Drops_LesserEldritchIchors,
        Minion_Drops_GreaterEldritchIchors,
        Minion_Drops_GrandEldritchIchors,
        Minion_Drops_EldritchChaosOrbs,
        Minion_Drops_EldritchExaltedOrbs,
        Minion_Drops_EldritchAnnulmentOrbs,
        //Scarabs
        Minion_Drops_Rusted_Breach_Scarab,
        Minion_Drops_Polished_Breach_Scarab,
        Minion_Drops_Gilded_Breach_Scarab,
        Minion_Drops_Rusted_Elder_Scarab,
        Minion_Drops_Polished_Elder_Scarab,
        Minion_Drops_Gilded_Elder_Scarab,
        Minion_Drops_Rusted_Sulphite_Scarab,
        Minion_Drops_Polished_Sulphite_Scarab,
        Minion_Drops_Gilded_Sulphite_Scarab,
        Minion_Drops_Rusted_Ambush_Scarab,
        Minion_Drops_Polished_Ambush_Scarab,
        Minion_Drops_Gilded_Ambush_Scarab,
        Minion_Drops_Rusted_Harbinger_Scarab,
        Minion_Drops_Polished_Harbinger_Scarab,
        Minion_Drops_Gilded_Harbinger_Scarab,
        Minion_Drops_Rusted_Expedition_Scarab,
        Minion_Drops_Polished_Expedition_Scarab,
        Minion_Drops_Gilded_Expedition_Scarab,
        Minion_Drops_Rusted_Legion_Scarab,
        Minion_Drops_Polished_Legion_Scarab,
        Minion_Drops_Gilded_Legion_Scarab,
        Minion_Drops_Rusted_Abyss_Scarab,
        Minion_Drops_Polished_Abyss_Scarab,
        Minion_Drops_Gilded_Abyss_Scarab,
        Minion_Drops_Rusted_Bestiary_Scarab,
        Minion_Drops_Polished_Bestiary_Scarab,
        Minion_Drops_Gilded_Bestiary_Scarab,
        Minion_Drops_Rusted_Torment_Scarab,
        Minion_Drops_Polished_Torment_Scarab,
        Minion_Drops_Gilded_Torment_Scarab,
        Minion_Drops_Rusted_Metamorph_Scarab,
        Minion_Drops_Polished_Metamorph_Scarab,
        Minion_Drops_Gilded_Metamorph_Scarab,
        Minion_Drops_Rusted_Blight_Scarab,
        Minion_Drops_Polished_Blight_Scarab,
        Minion_Drops_Gilded_Blight_Scarab,
        Minion_Drops_Rusted_Reliquary_Scarab,
        Minion_Drops_Polished_Reliquary_Scarab,
        Minion_Drops_Gilded_Reliquary_Scarab,
        Minion_Drops_Rusted_Divination_Scarab,
        Minion_Drops_Polished_Divination_Scarab,
        Minion_Drops_Gilded_Divination_Scarab,
        Minion_Drops_Rusted_Shaper_Scarab,
        Minion_Drops_Polished_Shaper_Scarab,
        Minion_Drops_Gilded_Shaper_Scarab,
        Minion_Drops_Rusted_Cartography_Scarab,
        Minion_Drops_Polished_Cartography_Scarab,
        Minion_Drops_Gilded_Cartography_Scarab,
        //Div Cards
        Minion_Drops_DivCard_Rewards_Currency,
        Minion_Drops_DivCard_Rewards_BasicCurrency,
        Minion_Drops_DivCard_Rewards_LeagueCurrency,
        Minion_Drops_DivCard_Rewards_OtherDivCards,
        Minion_Drops_DivCard_Rewards_Gems,
        Minion_Drops_DivCard_Rewards_LevelledGems,
        Minion_Drops_DivCard_Rewards_QualityGems,
        Minion_Drops_DivCard_Rewards_Unique,
        Minion_Drops_DivCard_Rewards_UniqueWeapon,
        Minion_Drops_DivCard_Rewards_UniqueArmour,
        Minion_Drops_DivCard_Rewards_UniqueJewellery,
        Minion_Drops_DivCard_Rewards_CorruptedUnique,
        Minion_Drops_DivCard_Rewards_Map,
        Minion_Drops_DivCard_Rewards_UniqueMap,
        Minion_Drops_DivCard_Rewards_CorruptedItem,

    }
    public enum AltarDownsides
    {
        Boss_Gains_ConsecratedGroundOnHit,
        Boss_Gains_FireRes_ChaosRes,
        Boss_Gains_Armour,
        Boss_Gains_PhysicalAsExtraFire,
        Boss_Gains_Ignite,
        Boss_Gains_Poison,
        Boss_Gains_EnemiesLoseFlaskCharges,
        Boss_Gains_PhysicalAsExtraRandomElement_Penetration,
        Boss_Gains_HitsInflictMalediction,
        Boss_Gains_PhysicalAsExtraChaos,
        Boss_Gains_ArmourPercentEvasionPercent,
        Boss_Gains_EnemiesAreHindered,

        Minion_Gains_DropsBurningGroundOnDeath,
        Minion_Gains_CreateConsecratedGroundOnDeath,
        Minion_Gains_PhysicalAsExtraRandomElement_Exposure,
        Minion_Gains_EnemiesLoseFlaskCharges,
        Minion_Gains_FireRes_ChaosRes,
        Minion_Gains_Armour,
        Minion_Gains_AOE,
        Minion_Gains_Evasion,
        Minion_Gains_Ignite,
        Minion_Gains_Poison,
        Minion_Gains_VulnerabilityOnHit,
        Minion_Gains_PhysicalAsExtraChaos,
        Minion_Gains_PhysicalAsExtraFire,

        Player_Gains_Minus_FireRes_ChaosRes,
        Player_Gains_Minus_Armour_Evasion,
        Player_Gains_IncreasedFlaskChargesUsed,
        Player_Gains_TakeChaosDamagePerSecond_DuringFlaskEffect,
        Player_Gains_SpellHitsHinderYou,
        Player_Gains_AllDamageTakenFromHitsCanScorchYou,
        Player_Gains_CursesYouInflictAreReflectedBackToYou,
        Player_Gains_EnemiesDropBurningGroundWhenHittingYou,
        Player_Gains_ChanceToBeTargetedByAMeteorWhenYouUseAFlask,
        Player_Gains_NearbyEnemiesGainPhysicalAsExtraFire,
        Player_Gains_NearbyEnemiesGainPhysicalAsExtraChaos,
    }
    public enum AffectedTarget
    {
        Any = 0,
        Player = 1,
        Minions = 2,
        FinalBoss = 3,
    }
    public enum EffectType
    {
        Neutral,
        Upside,
        Downside,
    }
}
